const List<String> drunkardConversation = [
  "Let's celebrate this moment!",
  "What's your favorite drink here?",
  "To new friendships and old memories!",
  "Feeling the rhythm of the night!",
  "No work tomorrow, just fun!",
  "Another round, my friend!",
  "Singing karaoke later, eh?",
  "The night is young and so are we!",
  "Lost in the joy of good company!",
  "To the ones who make us laugh!",
  "Laughter is the best medicine!",
  "A toast to happiness and laughter!",
  "Making memories, one sip at a time!",
  "Cheers to the wild and free!",
  "In the mood for a good story?",
];

const List<String> noviceConversation = [
  "Greetings, fellow adventurer!",
  "How can I assist you today?",
  "Ready for a noble quest?",
  "In need of guidance, friend?",
  "Training hard, ready to help.",
  "Seeking wisdom? Just ask.",
  "Tell me your tale, traveler.",
  "Dreaming of heroic deeds?",
  "What brings you to my path?",
  "Questions? I'm at your service.",
  "Adventures await us both!",
  "Looking for a brave companion?",
  "Together we shall triumph!",
  "Speak, and I shall listen.",
  "Eager for a worthy cause?",
  "May our swords stay true.",
];

const List<String> whiteKnightConversation = [
  "Hail, noble friend!",
  "Defending honor and justice.",
  "How may I aid thee?",
  "In service to the realm.",
  "Valor guides my blade.",
  "Champion of righteousness.",
  "A shield against darkness.",
  "Noble deeds await.",
  "Ask, and I shall answer.",
  "Bound by the knight's code.",
  "Duty calls, as does honor.",
  "Wielding a pure heart.",
  "For a realm of harmony.",
  "A white knight stands ready.",
  "Ever vigilant, ever just.",
  "Together for the light!",
];

const List<String> darkWizardConversation = [
  "Bow before my power!",
  "What do you want, mortal?",
  "My spells surpass all.",
  "I wield dark mysteries.",
  "Power at my fingertips.",
  "Foolish to challenge me.",
  "I command the shadows.",
  "Knowledge beyond you.",
  "Bask in my dark aura.",
  "Fear the arcane might!",
  "My magic knows no bounds.",
  "You seek my dark wisdom?",
  "Witness my sorcery.",
  "The shadows obey me.",
  "Bow to the dark master.",
  "Darkness bows to me.",
];
